### ISSUE TITLE
http://localhost:2000/proxy.pac fails because can't find module 'pug'

### ISSUE THREAD

**Issue by airtonix** [jeansaad/chalet#39]
```
Error: Cannot find module 'pug'
Require stack:
- /THEPROJECT/node_modules/.store/express-npm-4.18.2-bb15ff679a/node_modules/express/lib/view.js
- /THEPROJECT/node_modules/.store/express-npm-4.18.2-bb15ff679a/node_modules/express/lib/application.js
- /THEPROJECT/node_modules/.store/express-npm-4.18.2-bb15ff679a/node_modules/express/lib/express.js
- /THEPROJECT/node_modules/.store/express-npm-4.18.2-bb15ff679a/node_modules/express/index.js
- /THEPROJECT/node_modules/.store/chalet-npm-0.10.2-0595cc1a69/node_modules/chalet/lib/daemon/app.js
- /THEPROJECT/node_modules/.store/chalet-npm-0.10.2-0595cc1a69/node_modules/chalet/lib/daemon/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new View (/THEPROJECT/node_modules/.store/express-npm-4.18.2-bb15ff679a/node_modules/express/lib/view.js:81:14)
    at Function.render (/THEPROJECT/node_modules/.store/express-npm-4.18.2-bb15ff679a/node_modules/express/lib/application.js:587:12)
    at ServerResponse.render (/THEPROJECT/node_modules/.store/express-npm-4.18.2-bb15ff679a/node_modules/express/lib/response.js:1039:7)
    at pac (/THEPROJECT/node_modules/.store/chalet-npm-0.10.2-0595cc1a69/node_modules/chalet/lib/daemon/routers/index.js:21:11)
    at Layer.handle [as handle_request] (/THEPROJECT/node_modules/.store/express-npm-4.18.2-bb15ff679a/node_modules/express/lib/router/layer.js:95:5)
    at next (/THEPROJECT/node_modules/.store/express-npm-4.18.2-bb15ff679a/node_modules/express/lib/router/route.js:144:13)
```

**Comment by airtonix** [comment]
`package.json`

```json
{
  "name": "iframe-storage-mediator",
  "packageManager": "yarn@3.3.0",
  "type": "module",
  "dependencies": {
    "@mdx-js/mdx": "^2.1.1",
    "@mdx-js/react": "^2.1.1",
    "@mdx-js/rollup": "^2.1.1",
    "@types/node": "^17.0.31",
    "@types/node-fetch": "^2.5.12",
    "@types/react": "^18.0.8",
    "@types/react-dom": "^18.0.3",
    "@vitejs/plugin-react": "^2.2.0",
    "chalet": "^0.10.2",
    "cookie-toss": "^2.0.4",
    "cross-fetch": "^3.1.5",
    "hotel": "^0.8.7",
    "node-fetch": "^2.6.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-streaming": "^0.3.5",
    "syncpack": "^8.3.9",
    "typescript": "^4.8.4",
    "vite": "^3.0.4",
    "vite-plugin-ssr": "0.4.52"
  }
}

```
